name: 'Web API Build'

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - backend/**
      - .github/workflows/dotnet-webapp-build.yml

env:
  DOTNET_VERSION: '8.x'
  ENV: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }}
  REGISTRY_LOGIN_SERVER: 'acrhubshared${{ vars.APP_LOCATION }}.azurecr.io'
    
jobs:
  build-code:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: "./backend"

    steps:
    - name: "Checkout Github Action"
      uses: actions/checkout@v4

    - name: "Setup .NET ${{ env.DOTNET_VERSION }}"
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: "Install dependencies"
      run: dotnet restore

    - name: "Build"
      run: dotnet build --no-restore
      
    - name: "Test"
      run: dotnet test --no-build --verbosity normal

  # build-image:
  #   runs-on: ubuntu-latest

  #   defaults:
  #     run:
  #       shell: bash
  #       working-directory: "./backend/src"

  #   steps:
  #   - name: "Checkout Github Action"
  #     uses: actions/checkout@v4

  #   - name: "Login to ACR"
  #     id: login
  #     uses: docker/login-action@v3
  #     with:
  #       registry: ${{ env.REGISTRY_LOGIN_SERVER }}
  #       username: ${{ secrets.AZURE_CLIENT_ID }}
  #       password: ${{ secrets.AZURE_CLIENT_SECRET }}

  #   - name: "Build image"
  #     if: steps.login.outcome == 'success'
  #     run: |
  #       docker build . --file Dockerfile --tag ${{ vars.APP_NAME }}-${{ env.ENV }}:${{ github.sha }}