name: Build .NET Web App

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - backend/**
      - .github/workflows/dotnet-webapp-build.yml
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.x'
    
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./backend"

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal