name: 'Web API Deployment'

on:
  push:
    branches:
      - develop
      - main
    paths:
      - backend/**
      - .github/workflows/dotnet-webapp-deploy.yml
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.x'
  ENV: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }}
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: "./backend/src"

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        run: |
          az login --service-principal \
            --user ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: 'Login to ACR'
        id: login
        uses: docker/login-action@v3
        with:
          registry: "acr${{ vars.APP_NAME }}${{ env.ENV }}${{ vars.APP_LOCATION }}.azurecr.io"
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: 'Build image and push to ACR'
        if: steps.login.outcome == 'success'
        run: |
          docker build . -t acr${{ vars.APP_NAME }}${{ env.ENV }}${{ vars.APP_LOCATION }}.azurecr.io/${{ vars.APP_NAME }}:${{ github.sha }}
          docker push acr${{ vars.APP_NAME }}${{ env.ENV }}${{ vars.APP_LOCATION }}.azurecr.io/${{ vars.APP_NAME }}:${{ github.sha }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-${{ vars.APP_NAME }}-${{ env.ENV }}-${{ vars.APP_LOCATION }}'
          images: "acr${{ vars.APP_NAME }}${{ env.ENV }}${{ vars.APP_LOCATION }}.azurecr.io/${{ vars.APP_NAME }}:${{ github.sha }}"
    
      - name: 'Set environment variables'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'app-${{ vars.APP_NAME }}-${{ env.ENV }}-${{ vars.APP_LOCATION }}'
          app-settings-json: |
            [
                {
                    "name": "WEBSITES_PORT",
                    "value": "8080",
                    "slotSetting": false
                }
            ]

      - name: 'Azure logout'
        run: |
          az logout