name: 'Web API Deployment'

on:
  push:
    branches:
      - develop
      - main
    paths:
      - backend/**
      - .github/workflows/dotnet-webapp-deploy.yml
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.x'
  ENV: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }}
  REGISTRY_LOGIN_SERVER: 'acrhubshared${{ vars.APP_LOCATION_SHORT }}.azurecr.io'
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: "./backend/src"

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        run: |
          az login --service-principal \
            --user ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: 'Login to ACR'
        id: login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: 'Build image and push to ACR'
        if: steps.login.outcome == 'success'
        run: |
          docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ vars.APP_NAME }}-${{ env.ENV }}:${{ github.sha }}
          docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ vars.APP_NAME }}-${{ env.ENV }}:${{ github.sha }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-${{ vars.APP_NAME }}-${{ env.ENV }}-${{ vars.APP_LOCATION_SHORT }}'
          images: '${{ env.REGISTRY_LOGIN_SERVER }}/${{ vars.APP_NAME }}-${{ env.ENV }}:${{ github.sha }}'
    
      - name: 'Azure logout'
        run: |
          az logout